### ISSUE TITLE
Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by Shivanshmundra** [avinashpaliwal/Super-SloMo#17] opened 2019-01-06 11:04 UTC
I am getting this error when I am running with gpu, it is running fine with cpu though.
May be in doing temporary fix for #7 , this error was introduced and I am not able to figure it out.

```    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 mjpeg
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
frame=   72 fps=0.0 q=2.0 Lsize=N/A time=00:00:03.00 bitrate=N/A    
video:2098kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
  0%|                                                                          | 0/71 [00:00<?, ?it/s]/users/TeamVideoSummarization/.local/lib/python2.7/site-packages/torch/nn/functional.py:1820: UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.")
cuda:0

Traceback (most recent call last):
  File "video_to_slomo.py", line 218, in <module>
    main()
  File "video_to_slomo.py", line 185, in main
    g_I0_F_t_0 = flowBackWarp(I0, F_t_0)
  File "/users/TeamVideoSummarization/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/users/TeamVideoSummarization/shivansh/Super-SloMo/model.py", line 276, in forward
    x = self.gridX.unsqueeze(0).expand_as(u).float() + u
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #3 'other'
```
Pardon if this was silly doubt.

**Comment by avinashpaliwal** [comment] 2019-01-07 04:15
This error normally occurs  when the device [here](https://github.com/avinashpaliwal/Super-SloMo/blob/e8508bd949e51985ba73b99d0063090cec7e3679/video_to_slomo.py#L149) and [here](https://github.com/avinashpaliwal/Super-SloMo/blob/e8508bd949e51985ba73b99d0063090cec7e3679/video_to_slomo.py#L150) is "cpu" while at other places it is "cuda:0" / gpu. Basically the flow back warper is on cpu while the tensor is on gpu. How are you changing the code to run on CPU/GPU. Did you make any modification to the code?

**Comment by Shivanshmundra** [comment] 2019-01-07 07:59
@avinashpaliwal  I just changed ```device = "cpu"``` so that PyTorch uses cpu forcefully in code [here](https://github.com/avinashpaliwal/Super-SloMo/blob/e8508bd949e51985ba73b99d0063090cec7e3679/video_to_slomo.py#L116). 
I tried exporting model and data to cuda device after they were loaded but still, same error occurred.

**Comment by avinashpaliwal** [comment] 2019-01-08 01:15
When you are manually exporting the model try to set [this](https://github.com/avinashpaliwal/Super-SloMo/blob/e8508bd949e51985ba73b99d0063090cec7e3679/video_to_slomo.py#L149) and the device on the next line to cuda as well.

**Comment by Shivanshmundra** [comment] 2019-01-08 07:07
I used the pre-trained model given by you and changed the variable ```device``` value to ```cpu/cuda:0```. So Every line now should have used the value of device variable and hence should not be a problem due to that.
If you can once try to convert any video to slowmo by pretrained model from latest commit in this branch, it would imply that I am making mistake somewhere.

**Comment by avinashpaliwal** [comment] 2019-01-09 00:03
I have tested it and it's working fine. My configuration is: PyTorch 0.4.1, python 3.6.7, Cuda 9.2, Windows. I have not tested it with other configurations and therefore can't say for sure about the issues that will crop up. 

- Was the script working for you at some point? 
- Did you also try running from a fresh clone/fork? 
- If some version of the code was working, then take a diff between the two versions of scripts (maybe also other dependent files) and make incremental changes to the working code to find out where the problem is.

**Comment by avinashpaliwal** [comment] 2019-02-21 17:02
I am assuming that your issue was addressed and closing this issue.

**Closed by avinashpaliwal** 2019-02-21 17:02 UTC
